// <auto-generated />
namespace Grp8MovieShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class JunctionTableConceptupd2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JunctionTableConceptupd2));
        
        string IMigrationMetadata.Id
        {
            get { return "202012281447564_JunctionTableConceptupd2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
